languageCode = "en"
languageName = "English"
weight = 1
title = "Max's Tech Chronicles"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Massimiliano Donini"
image = "avatar.jpg"
links = [ { github = "https://github.com/ilmax" }, { linkedin = "https://www.linkedin.com/in/massimiliano-donini/" }, { x-twitter = "https://x.com/maxx_don" } ]
headline = "Software Architecture | Cloud | dotnet | DevOps | Raspberry PI all the things 🚀"
bio = "🔭 I’m currently working as a freelance Cloud Architect in The Netherlands 🇳🇱 I’m looking to collaborate on Azure and the dotnet technology landscape 💬 Ask me about Azure, dotnet, EF Core, ASP.NET Core, terraform, GitHub & CI/CD automation"
