colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
defaultFeaturedImage = ""
highlightCurrentMenuArea = "enable"
defaultBackgroundImage = "background.jpg"
smartTOC = "true"

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "hero"
homepageImage = "background.jpg"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = true
showComments = true
sharingLinks = [ "email", "facebook", "linkedin", "twitter", "bluesky" ]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = "show"
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true

[term]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]

[giscus]
repo = 'ilmax/site'
repoID = 'R_kgDOIvGqCw'
category = 'Post Comments'
categoryID = 'DIC_kwDOIvGqC84CTeD0'
mapping = 'pathname'
strict = 1
reactionsEnabled = '1'
emitMetadata = '0'
inputPosition = 'bottom'
theme = 'cobalt'
lang = 'en'
loading = 'lazy'