baseURL = "https://ilmax.github.io/site/"
languageCode = "en-us"
title = "Massimiliano Donini's Tech Blog"
theme = "m10c"
avatar = "/static/images/avatar/me/png"

[params]
  author = "Massimiliano Donini"
  description = "My adventures in Tech"
  
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#3399ff"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ilmax"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/maxx_don"