baseURL = "https://ilmax.github.io/"
languageCode = "en-us"
title = "Massimiliano Donini's Tech Blog"
theme = "m10c"
enableRobotsTXT = true
paginate = 8

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  author = "Massimiliano Donini"
  description = "My adventures in Tech"
  menu_item_separator = " | "

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#3399ff"

  [params.giscus]
    repo = "ilmax/site"
    repoID = "R_kgDOIvGqCw"
    category = "Post Comments"
    categoryID = "DIC_kwDOIvGqC84CTeD0"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "dark_dimmed"
    lang = "en"
    loading = "lazy"    

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ilmax"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/maxx_don"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/massimiliano-donini/"