baseURL: 'https://maxdon.tech'
languageCode: en-us
title: Massimiliano's Tech Chronicles
theme: m10c
enableRobotsTXT: true
paginate: 8
googleAnalytics: G-QK96EXLDNF
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
params:
  favicon: /favicon.ico
  author: Massimiliano Donini
  description: My adventures in Tech
  menu_item_separator: ' | '
  style:
    darkestColor: '#242930'
    darkColor: '#353b43'
    lightColor: '#afbac4'
    lightestColor: '#ffffff'
    primaryColor: '#3399ff'
  shareButtons:
    size: small
    networks:
      - facebook
      - twitter
      - email
      - reddit
    icon: solid
    buttonMargin: 0.2em
  giscus:
    repo: ilmax/ilmax.github.io
    repoID: R_kgDOI1C2VQ
    category: Comments
    categoryID: DIC_kwDOI1C2Vc4CTw93
    mapping: pathname
    strict: 1
    reactionsEnabled: '1'
    emitMetadata: '0'
    inputPosition: bottom
    theme: dark_dimmed
    lang: en
    loading: lazy
  social:
    - icon: github
      name: GitHub
      url: 'https://github.com/ilmax'
    - icon: twitter
      name: Twitter
      url: 'https://twitter.com/maxx_don'
    - icon: linkedin
      name: LinkedIn
      url: 'https://www.linkedin.com/in/massimiliano-donini/'

taxonomies:
  category: categories
  tag: tags
  series: series
