name: "Compress Images"
description: "Compress all images from the provided directory"
author: "Clyde D'Souza & Massimiliano Donini"

outputs:
  has-changes:
    description: "Indicates whether or not images have been changed"
    value: ${{ steps.changed-files.outputs.any_changed }}

runs:
  using: "composite"
  steps:
    - name: Install required npm packages
      shell: bash
      run: |
        npm install --global @343dev/optimizt

    - name: Run image compression
      shell: bash
      id: changed-files
      run: |
        head_of_main=$(git rev-parse origin/main)
        head_of_current=$(git rev-parse HEAD)
        changed_images=$(git diff --name-only $head_of_main $head_of_current '***.png' '***.jpg' ' ***.jpeg' '***.svg' '***.webp')
        echo Checking for changed images...
        if [ -z "$changed_images" ]; then
          echo "No images have been changed"
          echo "any_changed=false" >> $GITHUB_OUTPUT
        else
          echo "Images have been changed, starting image compression..."
          echo $changed_images | xargs -n 1 optimizt -l -f
          changed=$(git diff --shortstat | wc -l)
          if [ $changed -gt 0 ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi
        fi
