name: "Compress Images"
description: "Compress all images from the provided directory"
author: "Clyde D'Souza & Massimiliano Donini"

outputs:
  has-changes:
    description: "Indicates whether or not images have been changed"
    value: ${{ steps.changed-files.outputs.any_changed }}

runs:
  using: "composite"
  steps:
    - name: Install required npm packages
      shell: bash
      run: |
        npm install --global @343dev/optimizt

    - name: Get sha of the last commit
      shell: bash
      id: last-commit
      run: |
        echo "sha=$(git rev-parse origin/main)" >> $GITHUB_ENV

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        base_sha: ${{ env.sha }}
        files: |
          **.jpg
          **.jpeg
          **.png
          **.svg
          **.webp

    - name: Run image compression
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo compressing image $file 
          optimizt --verbose -l $file
        done
