name: Build Hugo site

on: pull_request

permissions:
  contents: read

jobs:
  # Build The Hugo Site
  build:
    name: Build Hugo site
    env:
      HUGO_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Build Hugo site
        uses: ./.github/build