name: Optimize images

on:
  issue_comment:
    types: [created]

jobs:
  optimize-images:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/optimize images')
    name: Optimize images
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Like comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              comment_id: ${{ github.event.comment.id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1'
            })

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout PR branch
        run: git checkout --progress --force refs/remotes/pull/${{ github.event.issue.number }}/merge

      - name: Optimize images
        id: optimize-images
        uses: ./.github/optimize-images

      - name: Push changes
        if: ${{ steps.optimize-images.outputs.has-changes == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Optimized images added in PR
          commit_options: "--signoff"

      - name: Add success comment
        uses: actions/github-script@v7
        if: ${{ steps.optimize-images.outputs.has-changes == 'true' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Images optimized successfully! 🎉'
            })

      - name: Add no changes comment
        uses: actions/github-script@v7
        if: ${{ steps.optimize-images.outputs.has-changes != 'true' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey, looks like there\u0027s nothing to optimize here 🤷‍♂️'
            })
